#!/bin/bash -eu
#
# Bootstrap script for dotbot. Snatched with modification on variable value.
# Refs: https://github.com/anishathalye/dotbot/blob/840cd164d20713a8e34f3aeb4ab1121c9745fad9/tools/git-submodule/install

# dotfiles root repository absolute path
BASEDIR="$(git rev-parse --show-toplevel || echo "/dev/null")"

CONFIG="${BASEDIR}/.config/dotbot/install.conf.yaml"
DOTBOT_DIR="${BASEDIR}/.local/lib/dotbot"

if [[ ! -x "${DOTBOT_DIR}/bin/dotbot" ]]; then
  echo -e "not managed by dotbot, skipped"
  exit 0
fi

git -C "${BASEDIR}" submodule update --init
git -C "${BASEDIR}" submodule update --init --recursive --checkout "${DOTBOT_DIR}"

# symlink
ln -sf "${BASEDIR}/.config/dotbot/install" "${BASEDIR}/install"

"${DOTBOT_DIR}/bin/dotbot" -d "${BASEDIR}" -c "${CONFIG}" "${@}"
