#!/bin/bash -eu
#
# Run bootstrap scripts inside `./bootstrap.d/`. Snatched with modification.
# Refs: https://github.com/TheLocehiliosan/yadm/blob/0a5e7aa353621bd28a289a50c0f0d61462b18c76/contrib/bootstrap/bootstrap-in-dir

# Save this file as ~/.config/yadm/bootstrap and make it executable. It will
# execute all executable files (excluding templates and editor backups) in the
# ~/.config/yadm/bootstrap.d directory when run.

BOOTSTRAP_D="${BASH_SOURCE[0]}.d"

if [[ ! -d "${BOOTSTRAP_D}" ]]; then
    echo "Error: bootstrap directory '${BOOTSTRAP_D}' not found" >&2
    exit 1
fi

# shellcheck disable=SC2312
find -L "${BOOTSTRAP_D}" -type f | sort | while IFS= read -r bootstrap; do
    if [[ -x "${bootstrap}" && ! "${bootstrap}" =~ "##" && ! "${bootstrap}" =~ "~$" ]]; then
        if ! "${bootstrap}"; then
            echo "Error: bootstrap '${bootstrap}' failed" >&2
            exit 1
        fi
    fi
done
