brew "bat"
brew "bcrypt"
brew "coreutils"
brew "diffutils"
brew "cups"
brew "exiftool"
brew "findutils"
brew "git"
brew "gnu-tar"
brew "grep"
brew "htop"
brew "imagemagick"
brew "jq"
brew "less"
brew "neofetch"
brew "neovim"
brew "shellcheck"
brew "telnet" if OS.mac?
brew "tmux"
brew "tree"
brew "zsh"

# https://alexos.dev/2022/01/02/docker-desktop-alternatives-for-m1-mac/
brew "docker"
brew "docker-buildx"
brew "docker-compose"
brew "colima" if OS.mac?

# gpg-related
brew "gnupg" if OS.mac?
brew "pinentry" if OS.mac?
